### ISSUE TITLE
NeoVim compatibility

### ISSUE THREAD

**Issue by JD557** [HerringtonDarkholme/vim-worksheet#2]
This plugin seems to not be working with NeoVim (It fails with a `IndexError('list index out of range',)`). It seems to work fine with normal Vim though.

I probably should fill this issue on the NeoVim repo, but I would like to get some feedback first (I'm not comfortable with writing vim plugins, so I'm finding a bit hard to find out what might be causing the problem).

**Comment by HerringtonDarkholme** [comment]
For neovim, I think you probably prefer this one. https://github.com/kassio/neoterm

What vim-worksheet do is identical to `TREPLSendFile`. 
neovim's async feature is really sweet, especially if you are evaluating large file or certain interpreter really sucks at speed.  With neovim's  terminal support, I think a worksheet-like feature is trivial to implement. Probably just several lines in .vimrc, with the help of neoterm.

**Comment by HerringtonDarkholme** [comment]
I will dig into neovim's compatibility problem later. `IndexError` is thrown from python, I guess it is a python plugin problem, though

**Comment by HerringtonDarkholme** [comment]
I found `vim.buffers` in neovim is the culprit. In vim we can subscript `vim.buffers` by `bufnr`, directly. But in neovim we have to minus one.

**Comment by HerringtonDarkholme** [comment]
https://github.com/neovim/neovim/issues/2823

**Comment by JD557** [comment]
Thanks for your help.

**Comment by justinmk** [comment]
https://github.com/neovim/neovim/issues/2823 was fixed in neovim python client 0.1.9

**Comment by HerringtonDarkholme** [comment]
Thanks!
